
apiVersion: v1
kind: Namespace
metadata:
  name: kanister
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: kanister
type: Opaque
data:
  minio_access_key_id: bWluaW8=
  minio_secret_access_key: bWluaW8xMjM=
